server:
#    image: server
    build: ./server/
    ports:
      - "8083:8083"
    net:
        mynet
rest:
#    image: rest
    build: ./rest/
    ports:
      - "8086:8086"
    net:
        mynet
bus:
#    image: bus
    build: ./bus/
    ports:
      - "8098:8098"
    net:
        mynet
wxproxy:
#    image: wxproxy
    build: ./wxproxy/
    ports:
      - "9098:9098"
    net:
        mynet
proxy:
#    image: proxy
    build: ./proxy/
    ports:
      - "8088:8088"
    net:
        mynet
elasticjob:
#    image: elasticjob
    build: ./elasticjob/
    ports:
      - "8080:8080"
    net:
        mynet