spring:
    messages:
        basename: lang/messages
datasource:
    boot:
        url: ${datasource.planes.url}
        username: ${datasource.planes.username}
        password: ${datasource.planes.password}
        driverClassName: com.mysql.cj.jdbc.Driver
        max-active: 30
        max-idle: 10
        max-wait: 10
        test-while-idle: true
log:
    path: ${logPath}
    level: ${logLevel}
server:
    port: 8081
